# RoR - Base Travis-CI Configuration for this project
language: ruby
rvm:
  - 2.3.1

env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_GC_HEAP_FREE_SLOTS=200000

services:
  - postgresql

before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  # Solves rainbow issue: https://github.com/sickill/rainbow/issues/48
  - gem update --system

before_script:
  - cd training-app
  - bundle install
  - psql -c "CREATE USER \"wbooks-api\" WITH PASSWORD 'wbooks-api';" -U postgres
  - psql -c "DROP DATABASE IF EXISTS \"training-app_test\";" -U postgres
  - psql -c "CREATE DATABASE \"training-app_test\" ENCODING 'utf8';" -U postgres
  - bundle exec rake db:migrate

script:
  - bundle exec rspec spec -fd
  - bundle exec rubocop app spec -R --format simple
  - bundle exec scss-lint app/assets/stylesheets/

#notifications:
#  email:
#    recipients:
#      - rails-bootstrap-dev@wolox.com.ar

cache:
bundler: true