# Rubocop project configuration
require: rubocop-rspec

Documentation:
  Enabled: false
LineLength:
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
