default: &default
    mailer_domain: <%= ENV["MAILER_DOMAIN"] %>
    mailer_password: <%= ENV["MAILER_PASSWORD"] %>
    mailer_user: <%= ENV["MAILER_USER"] %>
    mailer_address: <%= ENV["MAILER_ADDRESS"] %>
    mailer_port: <%= ENV["MAILER_PORT"] %>
    mailer_auth: <%= ENV["MAILER_AUTH"] %>
    mailer_email: <%= ENV["MAILER_EMAIL"] %>
    redis_password: <%= ENV["REDIS_PASSWORD"] %>
    redis_url: <%= ENV["REDIS_URL"] %>
    redis_namespace: <%= ENV["REDIS_NAMESPACE"] %>
development:
    <<: *default
    secret_key_base: 5c426750e9e53cf61ded59d7bc6142054cef52d2089f59b0f9279e96c43b7e63dc9f09d270cdd035d5624bb98f21fca1d41e80ed13b2a55fc44d828ee7c829d9
test:
    <<: *default
    secret_key_base: 52d0cd2dcdc81b037c0dc843bf48dea887693b16d3de00bfd613f511e2807c84b8e33b4a63644dadf06286c51d829c8ac91a77e00d66a2c9560fd3a3067a80fc
production:
    <<: *default
    secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
