common:
    mailer_domain: <%= ENV["MAILER_DOMAIN"] %>
    mailer_password: <%= ENV["MAILER_PASSWORD"] %>
    mailer_user: <%= ENV["MAILER_USER"] %>
    mailer_address: <%= ENV["MAILER_ADDRESS"] %>
    mailer_port: <%= ENV["MAILER_PORT"] %>
    mailer_auth: <%= ENV["MAILER_AUTH"] %>    
development:
    <<: *common
production:
    <<: *common
test:
    <<: *common
