development:
    mailer_domain: <%= ENV["MAILER_DOMAIN"] %>
    mailer_password: <%= ENV["MAILER_PASSWORD"] %>
    mailer_user: <%= ENV["MAILER_USER"] %>
    mailer_address: <%= ENV["MAILER_ADDRESS"] %>
    mailer_port: <%= ENV["MAILER_PORT"] %>
    mailer_auth: <%= ENV["MAILER_AUTH"] %>
    mailer_email: <%= ENV["MAILER_EMAIL"] %>
    google_api_key: <%= ENV['GOOGLE_CLIENT_ID'] %>
    google_secret_key: <%= ENV['GOOGLE_CLIENT_SECRET'] %>   
production:
    mailer_domain: <%= ENV["MAILER_DOMAIN"] %>
    mailer_password: <%= ENV["MAILER_PASSWORD"] %>
    mailer_user: <%= ENV["MAILER_USER"] %>
    mailer_address: <%= ENV["MAILER_ADDRESS"] %>
    mailer_port: <%= ENV["MAILER_PORT"] %>
    mailer_auth: <%= ENV["MAILER_AUTH"] %>
    mailer_email: <%= ENV["MAILER_EMAIL"] %>
    google_api_key: <%= ENV['GOOGLE_CLIENT_ID'] %>
    google_secret_key: <%= ENV['GOOGLE_CLIENT_SECRET'] %>    
test:
    mailer_domain: <%= ENV["MAILER_DOMAIN"] %>
    mailer_password: <%= ENV["MAILER_PASSWORD"] %>
    mailer_user: <%= ENV["MAILER_USER"] %>
    mailer_address: <%= ENV["MAILER_ADDRESS"] %>
    mailer_port: <%= ENV["MAILER_PORT"] %>
    mailer_auth: <%= ENV["MAILER_AUTH"] %>
    mailer_email: <%= ENV["MAILER_EMAIL"] %>
    google_api_key: <%= ENV['GOOGLE_CLIENT_ID'] %>
    google_secret_key: <%= ENV['GOOGLE_CLIENT_SECRET'] %>    